# Generated by Django 2.2.1 on 2019-05-25 19:31

from django.db import migrations, models
import facematch.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidentifiedperson',
            old_name='name',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='missingface',
            name='photo',
            field=models.ImageField(default=None, null=True, storage=facematch.storage_backends.MissingStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='unidentifiedface',
            name='photo',
            field=models.ImageField(default=None, null=True, storage=facematch.storage_backends.UnidentifiedStorage(), upload_to=''),
        ),
    ]
