# Generated by Django 2.2.1 on 2019-05-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190525_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facematch',
            options={'verbose_name_plural': 'Face Matches'},
        ),
        migrations.RemoveField(
            model_name='missingperson',
            name='age',
        ),
        migrations.RemoveField(
            model_name='unidentifiedperson',
            name='age',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='code',
            field=models.CharField(default=None, max_length=400, null=True),
        ),
    ]
