# Generated by Django 2.2.1 on 2019-05-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20190526_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingface',
            options={'ordering': ('person', 'id')},
        ),
        migrations.AlterModelOptions(
            name='unidentifiedface',
            options={'ordering': ('person', 'id')},
        ),
        migrations.AddField(
            model_name='facematch',
            name='human_says_no',
            field=models.BooleanField(default=True),
        ),
    ]
