# Generated by Django 2.2.1 on 2019-05-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190525_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingface',
            name='bounding_box',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unidentifiedface',
            name='bounding_box',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='code',
            field=models.CharField(default=None, max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unidentifiedperson',
            name='code',
            field=models.CharField(default=None, max_length=400, null=True, unique=True),
        ),
    ]
