# Generated by Django 2.2.1 on 2019-05-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20190526_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facematch',
            name='human_says_no',
        ),
        migrations.AddField(
            model_name='facematch',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
