# Generated by Django 2.2.1 on 2019-05-26 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20190526_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facematch',
            old_name='verified',
            new_name='human_says_maybe',
        ),
    ]
