# Generated by Django 2.2.1 on 2019-05-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20190526_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='facematch',
            name='human_verified',
            field=models.BooleanField(default=False),
        ),
    ]
