# Generated by Django 2.2.1 on 2019-05-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20190527_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='missing_max_age',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='missing_min_age',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
