# Generated by Django 2.2.1 on 2019-05-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20190527_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingperson',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='unidentifiedperson',
            options={'ordering': ('code',)},
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='last_sighted',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unidentifiedperson',
            name='last_sighted',
            field=models.DateField(default=None, null=True),
        ),
    ]
