# Generated by Django 2.2.1 on 2019-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20190527_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidentifiedperson',
            old_name='current_max_age',
            new_name='est_max_age',
        ),
        migrations.RemoveField(
            model_name='unidentifiedperson',
            name='current_min_age',
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='est_min_age',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
