# Generated by Django 2.2.1 on 2019-05-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_auto_20190527_0842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedperson',
            name='last_sighted',
        ),
    ]
