# Generated by Django 2.2.1 on 2019-05-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_remove_unidentifiedperson_last_sighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedperson',
            name='name',
        ),
    ]
