# Generated by Django 2.2.1 on 2019-05-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_remove_unidentifiedperson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='facematch',
            name='case_info_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facematch',
            name='case_info_last_check',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='facematch',
            name='case_info_matches',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facematch',
            name='case_info_reasons_non_match',
            field=models.TextField(default=None, null=True),
        ),
    ]
