# Generated by Django 2.2.1 on 2019-05-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20190527_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facematch',
            old_name='case_info_last_check',
            new_name='case_info_last_checked',
        ),
    ]
