# Generated by Django 2.2.1 on 2019-05-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_auto_20190527_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedperson',
            name='date_found',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='est_year_of_death_from',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
