# Generated by Django 2.2.1 on 2019-05-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20190527_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='facematch',
            name='human_notes',
            field=models.TextField(default=None, null=True),
        ),
    ]
