# Generated by Django 2.2.1 on 2019-05-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20190527_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedface',
            name='is_tattoo',
            field=models.BooleanField(default=False),
        ),
    ]
