# Generated by Django 2.2.1 on 2019-05-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_unidentifiedface_is_tattoo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedface',
            name='is_belt_buckle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unidentifiedface',
            name='is_watch',
            field=models.BooleanField(default=False),
        ),
    ]
