# Generated by Django 2.2.1 on 2019-05-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0020_auto_20190527_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedface',
            name='is_belt_buckle',
        ),
        migrations.RemoveField(
            model_name='unidentifiedface',
            name='is_tattoo',
        ),
        migrations.RemoveField(
            model_name='unidentifiedface',
            name='is_watch',
        ),
        migrations.AddField(
            model_name='unidentifiedface',
            name='object_type',
            field=models.CharField(choices=[('belt_buckle', 'belt buckle'), ('tattoo', 'tattoo'), ('watch', 'watch')], default=None, max_length=2, null=True),
        ),
    ]
