# Generated by Django 2.2.1 on 2019-05-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0021_auto_20190527_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidentifiedface',
            name='object_type',
            field=models.CharField(choices=[('', ''), ('belt_buckle', 'belt buckle'), ('tattoo', 'tattoo'), ('watch', 'watch')], default=None, max_length=100, null=True),
        ),
    ]
