# Generated by Django 2.2.1 on 2019-05-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0023_auto_20190527_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facematch',
            name='human_notes',
        ),
    ]
