# Generated by Django 2.2.1 on 2019-06-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0025_randomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='height_from',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='unidentifiedperson',
            name='height_from',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
